[package]
name = "rust-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = {version = "1.6.2", features=["behavior-version-latest"]}
aws-sdk-s3 = "1.85.0"
bytes = "1.10.1"
tokio = {version = "1.45.0", features = ["full"]}
